[package]
name = "iresearch-spider-rs"
version = "0.1.0"
edition = "2021"
authors = ["github.com/jerryshell/iresearch-spider-rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0" }
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.3"
csv = "1.1"
clap = { version = "3.0", features = ["derive"] }
