[package]
name = "iresearch-spider-rs"
version = "0.2.3"
edition = "2021"
repository = "https://github.com/jerryshell/iresearch-spider-rs"

[dependencies]
reqwest = { version = "0.11.13", default-features = false, features = [
    "json",
    "rustls-tls",
] }
tokio = { version = "1.24.1", features = ["full"] }
serde = "1.0.152"
serde_json = "1.0.91"
serde_derive = "1.0.152"
futures = "0.3.25"
csv = "1.1.6"
clap = { version = "4.0.32", features = ["derive"] }
anyhow = "1.0.68"

[profile.release]
lto = true
strip = true
