[package]
name = "iresearch-spider-rs"
version = "0.2.0"
edition = "2021"
authors = ["github.com/jerryshell/iresearch-spider-rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.9", default-features = false, features = [
    "json",
    "rustls-tls",
] }
tokio = { version = "1.15.0", features = ["full"] }
serde = "1.0.133"
serde_json = "1.0.74"
serde_derive = "1.0.133"
futures = "0.3.19"
csv = "1.1.6"
clap = { version = "3.0.7", features = ["derive"] }
anyhow = "1.0.52"
