[package]
name = "iresearch-spider-rs"
version = "0.2.2"
edition = "2021"
authors = ["github.com/jerryshell/iresearch-spider-rs"]

[dependencies]
reqwest = { version = "0.11.10", default-features = false, features = [
    "json",
    "rustls-tls",
] }
tokio = { version = "1.19.0", features = ["full"] }
serde = "1.0.137"
serde_json = "1.0.81"
serde_derive = "1.0.137"
futures = "0.3.21"
csv = "1.1.6"
clap = { version = "3.1.18", features = ["derive"] }
anyhow = "1.0.57"

[profile.release]
lto = true
strip = true
