on: [push]

name: ARMv7 build

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: iresearch-spider-rs-armv7
          path: ./target/armv7-unknown-linux-gnueabihf/release/iresearch-spider-rs
